# Generated by Django 3.2.4 on 2021-06-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('photo', models.FileField(upload_to='gallery/')),
            ],
        ),
    ]
