# Generated by Django 3.2.4 on 2021-06-20 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regis_app', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='propic',
            field=models.FileField(default=django.utils.timezone.now, upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
